import Head from "next/head";

import Curve from "@/components/Layout/Curve";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact | &lt;Olacodes/&gt;</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <h1 className="text-center mt-12 text-3xl">Contact</h1>
      </Curve>
    </>
  );
}
